/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Duc Thao
 */
public class Ratting extends javax.swing.JFrame {

    /**
     * Creates new form Ratting
     */
    Connection cn;
    static String USERST, USE,NAME;
    int MS;
    int c1 = 0, c2 = 0, c3 = 0, c4 = 0, c5 = 0;

    public Ratting(String S, String U) {
        initComponents();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        USERST = S;
        USE = U;
        img();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("ĐÁNH GIÁ");
        setResizable(false);
        try {
            PreparedStatement ps = cn.prepareStatement("select HOTEN from STYLELIST WHERE USENAMES=?");
            ps.setString(1, USERST);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                lblSTT.setText(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        S1 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        S4 = new javax.swing.JLabel();
        S5 = new javax.swing.JLabel();
        lblSao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSTT = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(197, 225, 165));

        jPanel1.setBackground(new java.awt.Color(197, 225, 165));

        jPanel2.setBackground(new java.awt.Color(197, 225, 165));

        S1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png"))); // NOI18N
        S1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S1MouseExited(evt);
            }
        });

        S3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png"))); // NOI18N
        S3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S3MouseExited(evt);
            }
        });

        S2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png"))); // NOI18N
        S2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                S2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S2MouseReleased(evt);
            }
        });

        S4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png"))); // NOI18N
        S4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S4MouseExited(evt);
            }
        });

        S5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png"))); // NOI18N
        S5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S5MouseExited(evt);
            }
        });

        lblSao.setText("0");

        jLabel6.setText("/");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/42655-star-icon (1).png"))); // NOI18N

        jLabel5.setText("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(S1)
                        .addGap(37, 37, 37)
                        .addComponent(S2)
                        .addGap(42, 42, 42)
                        .addComponent(S3)))
                .addGap(44, 44, 44)
                .addComponent(S4)
                .addGap(42, 42, 42)
                .addComponent(S5)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S5)
                    .addComponent(S4)
                    .addComponent(S2)
                    .addComponent(S3)
                    .addComponent(S1))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSao)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        txtGhichu.setBackground(new java.awt.Color(204, 204, 204));
        txtGhichu.setColumns(20);
        txtGhichu.setRows(5);
        txtGhichu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GHI CHÚ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N
        txtGhichu.setCaretColor(new java.awt.Color(197, 225, 165));
        jScrollPane1.setViewportView(txtGhichu);

        jButton1.setText("ĐÁNH GIÁ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("ĐÁNH GIÁ STYLE LIST");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Style List: ");

        lblSTT.setBackground(new java.awt.Color(0, 51, 51));
        lblSTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSTT.setForeground(new java.awt.Color(102, 0, 0));
        lblSTT.setText("Nguyễn Tuấn Anh");

        jPanel3.setBackground(new java.awt.Color(197, 225, 165));

        jLabel3.setText("Bạn có hài lòng về Style list này? Hãy đánh giá bằng số sao bên dưới bạn nhé!");

        jLabel4.setText("Hãy giúp chúng tôi cải thiện chất lượng dịch vụ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSTT))
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S1MouseClicked
        // TODO add your handling code here:
        MS = 1;
        c1 = 1;
        lblSao.setText(String.valueOf(MS));


    }//GEN-LAST:event_S1MouseClicked

    private void S1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S1MouseEntered
        // TODO add your handling code here:

        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));


    }//GEN-LAST:event_S1MouseEntered

    private void S1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S1MouseExited
        // TODO add your handling code here:
        if (c1 == 0) {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
        } else {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        }


    }//GEN-LAST:event_S1MouseExited

    private void S2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2MouseEntered
        // TODO add your handling code here:
        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
    }//GEN-LAST:event_S2MouseEntered

    private void S2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2MouseExited
        // TODO add your handling code here:
        if (c2 == 0) {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
        } else {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        }

    }//GEN-LAST:event_S2MouseExited

    private void S3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S3MouseEntered
        // TODO add your handling code here:
        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));

    }//GEN-LAST:event_S3MouseEntered

    private void S3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S3MouseExited
        // TODO add your handling code here:
        if (c3 == 0) {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
        } else {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        }

    }//GEN-LAST:event_S3MouseExited

    private void S4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S4MouseEntered
        // TODO add your handling code here:
        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S4.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
    }//GEN-LAST:event_S4MouseEntered

    private void S4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S4MouseExited
        // TODO add your handling code here:
        if (c4 == 0) {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S4.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
        } else {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S4.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        }
    }//GEN-LAST:event_S4MouseExited

    private void S5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S5MouseEntered
        // TODO add your handling code here:
        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S4.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        S5.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
    }//GEN-LAST:event_S5MouseEntered

    private void S5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S5MouseExited
        // TODO add your handling code here:
        if (c5 == 0) {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S4.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
            S5.setIcon(new ImageIcon(getClass().getResource("/icon/Holidays-Christmas-Star-icon.png")));
        } else {
            S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S3.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S4.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
            S5.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
        }

    }//GEN-LAST:event_S5MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = cn.prepareStatement("insert into rate\n"
                    + "values (?,?,?,?)");
            ps.setString(1, USERST);
            ps.setInt(2, MS);
            ps.setString(3, txtGhichu.getText());
            ps.setString(4, USE);

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Cảm ơn bạn đã đánh giá!");
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void S2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2MouseClicked
        // TODO add your handling code here:
        MS = 2;
        c2 = 1;
        lblSao.setText(String.valueOf(MS));

    }//GEN-LAST:event_S2MouseClicked

    private void S2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2MousePressed
        // TODO add your handling code here:
//        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
//        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
    }//GEN-LAST:event_S2MousePressed

    private void S2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2MouseReleased
        // TODO add your handling code here:
//        S1.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
//        S2.setIcon(new ImageIcon(getClass().getResource("/icon/42655-star-icon.png")));
    }//GEN-LAST:event_S2MouseReleased

    private void S3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S3MouseClicked
        // TODO add your handling code here:
        MS = 3;
        c3 = 1;
        lblSao.setText(String.valueOf(MS));
    }//GEN-LAST:event_S3MouseClicked

    private void S4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S4MouseClicked
        // TODO add your handling code here:
        MS = 4;
        c4 = 1;
        lblSao.setText(String.valueOf(MS));
    }//GEN-LAST:event_S4MouseClicked

    private void S5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S5MouseClicked
        // TODO add your handling code here:
        MS = 5;
        c5 = 1;
        lblSao.setText(String.valueOf(MS));
    }//GEN-LAST:event_S5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ratting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ratting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ratting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ratting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ratting(USERST, USE ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JLabel S5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSTT;
    private javax.swing.JLabel lblSao;
    private javax.swing.JTextArea txtGhichu;
    // End of variables declaration//GEN-END:variables
     private void img() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconhair.png")));
    }

}
